version: "3.9"

services:
  postgres:
    image: postgres:latest
    container_name: MovieWatchList-DB
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: MoviesDB
    ports:
      - "5432:5432"
    volumes:
      - MoviesDB_PostgreSQL:/var/lib/postgresql/data

volumes:
  MoviesDB_PostgreSQL:
