// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieWatchList.Migrations.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MovieWatchList.Migrations.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MovieWatchList.Migrations.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<double>("Rating")
                        .HasColumnType("double precision");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("Watched")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A mind-bending thriller about dreams within dreams.",
                            Director = "Christopher Nolan",
                            Genre = "Sci-Fi",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/2/2e/Inception_%282010%29_theatrical_poster.jpg",
                            Rating = 9.0,
                            ReleaseYear = 2010,
                            Title = "Inception",
                            Watched = false
                        },
                        new
                        {
                            Id = 2,
                            Description = "Batman fights crime in Gotham City.",
                            Director = "Christopher Nolan",
                            Genre = "Action",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/1/1c/The_Dark_Knight_%282008_film%29.jpg",
                            Rating = 9.5,
                            ReleaseYear = 2008,
                            Title = "The Dark Knight",
                            Watched = true
                        },
                        new
                        {
                            Id = 3,
                            Description = "A team of explorers travel through a wormhole in space.",
                            Director = "Christopher Nolan",
                            Genre = "Sci-Fi",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/b/bc/Interstellar_film_poster.jpg",
                            Rating = 8.8000000000000007,
                            ReleaseYear = 2014,
                            Title = "Interstellar",
                            Watched = false
                        },
                        new
                        {
                            Id = 4,
                            Description = "A hacker discovers the reality is a simulation.",
                            Director = "Lana Wachowski",
                            Genre = "Sci-Fi",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/d/db/The_Matrix.png",
                            Rating = 9.0,
                            ReleaseYear = 1999,
                            Title = "The Matrix",
                            Watched = true
                        },
                        new
                        {
                            Id = 5,
                            Description = "The Avengers assemble to undo Thanos' actions.",
                            Director = "Anthony Russo",
                            Genre = "Action",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/0/0d/Avengers_Endgame_poster.jpg",
                            Rating = 8.4000000000000004,
                            ReleaseYear = 2019,
                            Title = "Avengers: Endgame",
                            Watched = false
                        },
                        new
                        {
                            Id = 6,
                            Description = "The aging patriarch of an organized crime dynasty transfers control to his son.",
                            Director = "Francis Ford Coppola",
                            Genre = "Crime",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/1/1c/Godfather_ver1.jpg",
                            Rating = 9.1999999999999993,
                            ReleaseYear = 1972,
                            Title = "The Godfather",
                            Watched = true
                        },
                        new
                        {
                            Id = 7,
                            Description = "The lives of two mob hitmen, a boxer, and others intertwine.",
                            Director = "Quentin Tarantino",
                            Genre = "Crime",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/3/3b/Pulp_Fiction_%281994%29_poster.jpg",
                            Rating = 8.9000000000000004,
                            ReleaseYear = 1994,
                            Title = "Pulp Fiction",
                            Watched = false
                        },
                        new
                        {
                            Id = 8,
                            Description = "An insomniac office worker forms an underground fight club.",
                            Director = "David Fincher",
                            Genre = "Drama",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/f/fc/Fight_Club_poster.jpg",
                            Rating = 8.8000000000000007,
                            ReleaseYear = 1999,
                            Title = "Fight Club",
                            Watched = true
                        },
                        new
                        {
                            Id = 9,
                            Description = "The life story of Forrest Gump, a man with a low IQ.",
                            Director = "Robert Zemeckis",
                            Genre = "Drama",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/6/67/Forrest_Gump_poster.jpg",
                            Rating = 8.6999999999999993,
                            ReleaseYear = 1994,
                            Title = "Forrest Gump",
                            Watched = false
                        },
                        new
                        {
                            Id = 10,
                            Description = "Two imprisoned men bond over years, finding hope and redemption.",
                            Director = "Frank Darabont",
                            Genre = "Drama",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/8/81/ShawshankRedemptionMoviePoster.jpg",
                            Rating = 9.3000000000000007,
                            ReleaseYear = 1994,
                            Title = "The Shawshank Redemption",
                            Watched = true
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
